server.port=7000
server.ssl.enabled=false

spring.datasource.url=jdbc:h2:mem:simulatordb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.thymeleaf.cache=false

#simulator.hre.checksum-key=bduat@axis
#simulator.hre.checksum-key
simulator.cab.confirmation-url:http://localhost:7000/test-callback
simulator.cab.encryption-key=12345678901234567890123456789012
simulator.cab.checksum-key=12345678901234567890123456789012
simulator.cab.iv=SzdtUDJ4UTl2TDRuUjhzVA==

simulator.delay.default-seconds=5
simulator.delay.max-seconds=120
simulator.duplicate.second-call-delay-ms=1500